---
name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: yarn
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build
