---
name: test

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"
          cache: "npm"

      - name: install
        run: npm ci

      - name: Rebuild @swc/core
        run: npm rebuild @swc/core

      - name: test
        run: npm test -- --coverage --reporters=jest-junit
        env:
          JEST_JUNIT_CLASSNAME: junit.xml

      - name: codecov coverage
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: codecov test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
